apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - server/
  - ws-gateway/
  - web-client/
  - migrations/

labels:
  - pairs:
      app.kubernetes.io/name: chatapp
      app.kubernetes.io/managed-by: kustomize
